# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HS5o67Sj7a0GhPJBmz2dnR4XtiSuoR1l
"""

#crie um sistema que some 2 numeros

numeroy = 22
numerox = 12
print(numerox + numeroy)


#crie um sistema que imprima seu nome na tela

nome = "gustavo"

print(nome)

#crie um sistema que imprima seu nome e um cumprimento após nome ]


cumprimento = input("Digite seu nome - ")

print("olá " + cumprimento)

#crie um sistema para multiplicar dois numeros

numero1 = int(input("digite um numero - "))
numero2 = int(input("digite outro numero - "))

print( numero1 * numero2)